name: "Update"
description: "Update Article RSS"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  runs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - run: |
          ls
          pwd

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Update step
        run: "deno task update"

#    - name: Upload to Deno Deploy
#      uses: denoland/deployctl@v1
#      with:
#        project: "<your-project-name>"
#        entrypoint: "main.ts"
#        root: "."
