name: "Update"
description: "Update Article RSS"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  runs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Update step
        run: "deno task update"

      - name: Push File
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git add hello.txt
          git status
          git commit -m "[actions]: push files"
          git push origin main

#    - name: Upload to Deno Deploy
#      uses: denoland/deployctl@v1
#      with:
#        project: "<your-project-name>"
#        entrypoint: "main.ts"
#        root: "."
